### ISSUE TITLE
thread can't be block

### ISSUE THREAD

**Issue by zjsen668** [liquidsoft/alert.js#1]
When use the default window.alert,the code after the function will not be executed。But with this version, how to block the thread?

**Comment by liquidsoft** [comment]
Hey zjsen668.

Currently it is not possible to achieve that. You could do some workaround on the button callbakcs. I will try to make some time to research this a bit as it is, indeed, an interesting question.

**Comment by liquidsoft** [comment]
Update: After some research I found out it is not possible to achieve that with JS. A solution would be to put the rest of the script in the button callback or wrap it in a function and call it from the callback.
